org.gradle.jvmargs=-Xmx2G
modName=MoogsEndStructures
minecraftVersion=1.21
modVersion=2.0.1
modId=mes

# Mod metadata
modDescription=Lots of vanilla style structures to bring your end dimension to life! With plenty of mobs and great loot
modHomepage=https://www.curseforge.com/minecraft/mc-mods/moogs-end-structures
modSources=https://github.com/FinnSetchell/MoogsEndStructures
modIssues=https://github.com/FinnSetchell/MoogsEndStructures/issues
structureLibVersionRange=[1.1.0,)

# Publishing display customization
publishDisplayPrefix=MES
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=r4PuRGfV
curseforgeProjectId=892382
publishMcStart=1.21
publishMcEnd=1.21.11