org.gradle.jvmargs=-Xmx2G
modName=MoogsEndStructures
minecraftVersion=1.20
modVersion=2.0.1
modId=mes
modDescription=Lots of vanilla style structures to bring your end dimension to life! With plenty of mobs and great loot
modHomepage=https://www.curseforge.com/minecraft/mc-mods/moogs-end-structures
modSources=https://github.com/FinnSetchell/MoogsEndStructures
modReleases=https://github.com/FinnSetchell/MoogsEndStructures/releases
modIssues=https://github.com/FinnSetchell/MoogsEndStructures/issues
modDiscord=https://discord.gg/S5nffJbuvA
modKofi=https://ko-fi.com/finndog
modCurseforge=https://www.curseforge.com/minecraft/mc-mods/moogs-end-structures
modModrinth=https://modrinth.com/mod/moogs-end-structures

# Structure Lib dependency range (forge mods.toml)
structureLibVersionRange=[1.0.0,)

# Publishing display customization
publishDisplayPrefix=MES
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=r4PuRGfV
curseforgeProjectId=892382
curseforgeProjectSlug=moogs-end-structures
publishMcStart=1.20
publishMcEnd=1.20.6

# Discord webhook settings
discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/869/886/64/64/638285725964513688.png
discordEmbedColor=#3e0e49
discordThumbnailUrl=https://media.forgecdn.net/avatars/thumbnails/869/886/64/64/638285725964513688.png
discordBannerUrl=https://www.bisecthosting.com/images/CF/MES/BH_ME_HEADER.webp
discordRoleId=1466012771379581039
