
modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'GNU Lesser General Public License v3.0'
showAsResourcePack = false
mods = [
	{ modId = '${mod_id}', version = '${version}', displayName = "${mod_name}", description = '${mod_description}', logoFile = 'icon.png', credits = 'Built by Phantax', authors = 'FinnDog', displayURL = '${mod_homepage}' },
]
[[dependencies.mtr]]
modId = "moogs_structures"
mandatory = true
versionRange = "${structure_lib_version_range}"
ordering = "NONE"
side = "BOTH"
