"""
Generate a STRUCTURES.md listing every structure with its biome tag(s) and a link
to the start_pool. Doesn't include screenshots yet; those are TODO.

Run from project root: python scripts/structure_index.py
"""
import json
import sys
from collections import defaultdict
from pathlib import Path

from _paths import MOD_ID, STRUCTURES_DIR, PROJECT_ROOT

DATA = PROJECT_ROOT / "src" / "main" / "resources" / "data" / MOD_ID
STRUCTURE_JSONS = DATA / "worldgen" / "structure"
POOLS = DATA / "worldgen" / "template_pool"


def parse_pool(p):
    try:
        data = json.loads(p.read_text())
    except Exception:
        return []
    refs = []
    for elem in data.get("elements", []):
        e = elem.get("element", {})
        loc = e.get("location") or e.get("start_pool")
        if loc:
            refs.append(loc)
        for sub in e.get("elements", []):
            sloc = sub.get("element", {}).get("location") or sub.get("element", {}).get("start_pool")
            if sloc:
                refs.append(sloc)
    return refs


def collect_nbts(start_pool, pool_refs):
    visited, queue, found = set(), [start_pool], []
    while queue:
        cur = queue.pop()
        if not cur or cur in visited:
            continue
        visited.add(cur)
        for ref in pool_refs.get(cur, []):
            if ref.startswith(f"{MOD_ID}:"):
                rel = ref[len(MOD_ID) + 1:]
                if (STRUCTURES_DIR / f"{rel}.nbt").exists():
                    found.append(f"{rel}.nbt")
                else:
                    queue.append(ref)
    return found


def main():
    if not STRUCTURE_JSONS.exists():
        print(f"ERROR: Structure JSON dir not found at {STRUCTURE_JSONS}", file=sys.stderr)
        sys.exit(1)

    pool_refs = {}
    for pf in POOLS.rglob("*.json"):
        rel = str(pf.relative_to(POOLS).with_suffix("")).replace("\\", "/")
        pool_refs[f"{MOD_ID}:{rel}"] = parse_pool(pf)

    rows = []
    for sjson in sorted(STRUCTURE_JSONS.glob("*.json")):
        s_name = sjson.stem
        try:
            data = json.loads(sjson.read_text())
        except Exception as e:
            print(f"  [WARN] {s_name}: parse error {e}", file=sys.stderr)
            continue
        biome = data.get("biomes", "")
        if isinstance(biome, list):
            biome_str = ", ".join(biome)
        else:
            biome_str = biome
        nbts = collect_nbts(data.get("start_pool"), pool_refs) if data.get("start_pool") else []
        rows.append((s_name, biome_str, nbts))

    out = PROJECT_ROOT / "STRUCTURES.md"
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"# {MOD_ID.upper()} structures\n\n")
        f.write(f"_Auto-generated by `scripts/structure_index.py`. Don't edit by hand._\n\n")
        f.write(f"Total structures: **{len(rows)}**\n\n")

        # Group by biome (or first biome in list)
        by_biome = defaultdict(list)
        for s_name, biome, nbts in rows:
            primary = biome.split(",")[0].strip().replace("#" + MOD_ID + ":has_structure/", "").replace(f"#{MOD_ID}:", "")
            by_biome[primary or "unknown"].append((s_name, biome, nbts))

        for biome in sorted(by_biome.keys()):
            items = sorted(by_biome[biome])
            f.write(f"\n## {biome} ({len(items)})\n\n")
            f.write("| Structure | Biome tag(s) | NBT pieces |\n")
            f.write("|---|---|---|\n")
            for s_name, biome_str, nbts in items:
                nbt_list = ", ".join(f"`{n}`" for n in nbts[:3])
                if len(nbts) > 3:
                    nbt_list += f" (+{len(nbts) - 3} more)"
                if not nbts:
                    nbt_list = "-"
                f.write(f"| `{s_name}.json` | `{biome_str}` | {nbt_list} |\n")

        f.write(f"\n---\n_TODO: add screenshot links (one per structure) once available._\n")

    print(f"✓ wrote {out}")


if __name__ == "__main__":
    main()
