name: Release

on:
  push:
    tags:
      - '*.*.*-*'
      - '*.*.*-alpha.*-*'

permissions:
  contents: write

jobs:
  release:
    uses: FinnSetchell/release-actions/.github/workflows/release-v2.yml@v2
    secrets: inherit
