name: Release

on:
  push:
    tags:
      - '*.*.*-*.*.*'

permissions:
  contents: write

jobs:
  release:
    uses: FinnSetchell/release-actions/.github/workflows/release.yml@v1
    with:
      validate: true
      configPackTasks: publishCurseforgeDatapack publishModrinthDatapack
    secrets:
      MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
